device: "cpu"
max_gen_len: 20
flirty_threshold: 0.5

model_paths:
  detection_ckpt: "flirt_detection/models/flirt_detection_model.pt"
  generation_weights: "flirt_generation/flirty_response_model.h5"
  input_tokenizer: "flirt_generation/input_tokenizer.pkl"
  target_tokenizer: "flirt_generation/target_tokenizer.pkl"
